
create table pj(
shop_id	char(8),
_name	char(40),
alias	char(40),
province	char(8),
city	char(8),
city_pinyin	char(20),
city_id	char(3),
area	char(20),
big_cate	char(20),
big_cate_id	char(10),
small_cate	char(20),
small_cate_id	char(10),
address	char(200),
business_area	char(100),
phone	char(40),
hours	char(200),
avg_price	char(10),
stars	char(10),
photos	char(200),
description	char(200),
tags	char(200),
map_type	char(3),
original_latitude	char(10),
original_longitude	char(10),
google_longitude	char(10),
google_latitude	char(10),
navigation	char(200),
traffic	char(100),
atmosphere	char(100),
characteristics	char(50),
payment	char(10),
product_rating	char(5),
environment_rating	char(5),
service_rating	char(5),
all_remarks	char(200),
very_good_remarks	char(200),
good_remarks	char(200),
common_remarks	char(200),
bad_remarks	char(200),
very_bad_remarks	char(200),
recommended_dishes	char(200),
nearby_shops	char(200),
is_chains	char(200),
_group	varchar(300),
card char(200),
primary key(shop_id));

load data infile 'C:\pj.csv' into table pj fields terminated by ',' optionally enclosed by '"' escaped by '"' 
lines terminated by '\r\n'
ignore 1 lines; 
