LOAD DATA LOCAL INFILE '../data/data_2.csv' 
INTO TABLE city 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES; 

LOAD DATA LOCAL INFILE '../data/data_1.csv' 
INTO TABLE shop
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES; 

